language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install  --no-interaction --prefer-dist

script:
  - composer validate
  - ./vendor/bin/php-cs-fixer fix . --dry-run -v --level=psr2
